version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: samba-server-1
      APP_PORT: 548

  server:
    image: crazymax/samba
    network_mode: host
    volumes:
      - ${UMBREL_ROOT}/data/storage:/samba/share
    environment:
      - "TZ=Europe/Paris"
      - "SAMBA_LOG_LEVEL=0"
    restart: always